name: Auto-merge dependabot updates
on:
  schedule:
      # 16:00,17:00,18:00 in UTC+8
    - cron: "0 8,9,10 * * FRI"
jobs:
  test:
    name: Auto-merge dependabot updates
    runs-on: ubuntu-latest
    steps:
      - uses: akheron/dependabot-cron-action@v1
        with:
          token: ${{ secrets.MY_TOKEN }}
          auto-merge: minor
          merge-method: squash