name: CI
on:
  push:
    branches:
    - main
    - ci-**
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        node-version: ["16.x", "18.x"]
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    name: "lint in ${{ matrix.platform }} ${{ matrix.node-version }}"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: lint
        run: |
          yarn install --immutable
          yarn lint
  test:
    strategy:
      matrix:
        node-version: ["16.x", "18.x"]
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    name: "test in ${{ matrix.platform }} ${{ matrix.node-version }}"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: test
        run: |
          yarn install --immutable
          yarn build
          yarn test
  build-example:
    strategy:
      matrix:
        node-version: ["14.x", "16.x"]
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    name: "test in ${{ matrix.platform }} ${{ matrix.node-version }}"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: test
        run: |
          yarn install --immutable
          yarn build
          yarn example ./examples/crypto
          yarn example ./examples/erc20
          yarn example ./examples/flipper
          yarn example ./examples/inherent-flipper
          yarn example ./examples/lazy
          yarn example ./examples/mapping
          yarn example ./examples/vector
